
package fr.polytech.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Envoi", targetNamespace = "http://ws.polytech.fr/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Envoi {


    /**
     * 
     * @return
     *     returns fr.polytech.ws.Catalogue
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCatalogue", targetNamespace = "http://ws.polytech.fr/", className = "fr.polytech.ws.GetCatalogue")
    @ResponseWrapper(localName = "getCatalogueResponse", targetNamespace = "http://ws.polytech.fr/", className = "fr.polytech.ws.GetCatalogueResponse")
    @Action(input = "http://ws.polytech.fr/Envoi/getCatalogueRequest", output = "http://ws.polytech.fr/Envoi/getCatalogueResponse")
    public Catalogue getCatalogue();

    /**
     * 
     * @param arg1
     * @param arg0
     * @throws ExceptionArticle_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "ajouterPanier", targetNamespace = "http://ws.polytech.fr/", className = "fr.polytech.ws.AjouterPanier")
    @ResponseWrapper(localName = "ajouterPanierResponse", targetNamespace = "http://ws.polytech.fr/", className = "fr.polytech.ws.AjouterPanierResponse")
    @Action(input = "http://ws.polytech.fr/Envoi/ajouterPanierRequest", output = "http://ws.polytech.fr/Envoi/ajouterPanierResponse", fault = {
        @FaultAction(className = ExceptionArticle_Exception.class, value = "http://ws.polytech.fr/Envoi/ajouterPanier/Fault/ExceptionArticle")
    })
    public void ajouterPanier(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1)
        throws ExceptionArticle_Exception
    ;

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setCatalogue", targetNamespace = "http://ws.polytech.fr/", className = "fr.polytech.ws.SetCatalogue")
    @ResponseWrapper(localName = "setCatalogueResponse", targetNamespace = "http://ws.polytech.fr/", className = "fr.polytech.ws.SetCatalogueResponse")
    @Action(input = "http://ws.polytech.fr/Envoi/setCatalogueRequest", output = "http://ws.polytech.fr/Envoi/setCatalogueResponse")
    public void setCatalogue(
        @WebParam(name = "arg0", targetNamespace = "")
        Catalogue arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "viewCatalogue", targetNamespace = "http://ws.polytech.fr/", className = "fr.polytech.ws.ViewCatalogue")
    @ResponseWrapper(localName = "viewCatalogueResponse", targetNamespace = "http://ws.polytech.fr/", className = "fr.polytech.ws.ViewCatalogueResponse")
    @Action(input = "http://ws.polytech.fr/Envoi/viewCatalogueRequest", output = "http://ws.polytech.fr/Envoi/viewCatalogueResponse")
    public String viewCatalogue(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @throws ExceptionArticle_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "modifierPanier", targetNamespace = "http://ws.polytech.fr/", className = "fr.polytech.ws.ModifierPanier")
    @ResponseWrapper(localName = "modifierPanierResponse", targetNamespace = "http://ws.polytech.fr/", className = "fr.polytech.ws.ModifierPanierResponse")
    @Action(input = "http://ws.polytech.fr/Envoi/modifierPanierRequest", output = "http://ws.polytech.fr/Envoi/modifierPanierResponse", fault = {
        @FaultAction(className = ExceptionArticle_Exception.class, value = "http://ws.polytech.fr/Envoi/modifierPanier/Fault/ExceptionArticle")
    })
    public void modifierPanier(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2)
        throws ExceptionArticle_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "afficherCommande", targetNamespace = "http://ws.polytech.fr/", className = "fr.polytech.ws.AfficherCommande")
    @ResponseWrapper(localName = "afficherCommandeResponse", targetNamespace = "http://ws.polytech.fr/", className = "fr.polytech.ws.AfficherCommandeResponse")
    @Action(input = "http://ws.polytech.fr/Envoi/afficherCommandeRequest", output = "http://ws.polytech.fr/Envoi/afficherCommandeResponse")
    public String afficherCommande(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getNewPanier", targetNamespace = "http://ws.polytech.fr/", className = "fr.polytech.ws.GetNewPanier")
    @ResponseWrapper(localName = "getNewPanierResponse", targetNamespace = "http://ws.polytech.fr/", className = "fr.polytech.ws.GetNewPanierResponse")
    @Action(input = "http://ws.polytech.fr/Envoi/getNewPanierRequest", output = "http://ws.polytech.fr/Envoi/getNewPanierResponse")
    public int getNewPanier();

    /**
     * 
     * @param arg1
     * @param arg0
     * @throws ExceptionArticle_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "retirerPanier", targetNamespace = "http://ws.polytech.fr/", className = "fr.polytech.ws.RetirerPanier")
    @ResponseWrapper(localName = "retirerPanierResponse", targetNamespace = "http://ws.polytech.fr/", className = "fr.polytech.ws.RetirerPanierResponse")
    @Action(input = "http://ws.polytech.fr/Envoi/retirerPanierRequest", output = "http://ws.polytech.fr/Envoi/retirerPanierResponse", fault = {
        @FaultAction(className = ExceptionArticle_Exception.class, value = "http://ws.polytech.fr/Envoi/retirerPanier/Fault/ExceptionArticle")
    })
    public void retirerPanier(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1)
        throws ExceptionArticle_Exception
    ;

}
