
package fr.polytech.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ExceptionArticle", targetNamespace = "http://ws.polytech.fr/")
public class ExceptionArticle_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ExceptionArticle faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ExceptionArticle_Exception(String message, ExceptionArticle faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public ExceptionArticle_Exception(String message, ExceptionArticle faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: fr.polytech.ws.ExceptionArticle
     */
    public ExceptionArticle getFaultInfo() {
        return faultInfo;
    }

}
